version: '3.8'

services:
  postgres:
    image: postgres:13.1
    container_name: nestjs-database-connection-postgres-db
    restart: always
    environment:
      POSTGRES_USER: moMustafa
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: nestjs-db
    volumes:
      - nestjs_postgres_db:/data/postgres
    ports:
      - 5432:5432

  mongo:
    image: mongo-7.0.2
    container_name: nestjs-database-connection-mongo-db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - nestjs_mongo_db:/data/db

  adminer:
    image: adminer
    container_name: nestjs-database-connection-adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  nestjs_postgres_db:
  nestjs_mongo_db:
